motion_dim: 58
command_dim: 3
num_joints: 29
motion_mean:
- -0.15516217052936554
- -0.02112121507525444
- 0.0
- 0.703898549079895
- -0.05377127602696419
- 0.0
- -0.15516221523284912
- 0.02112121507525444
- 0.0
- 0.7038983106613159
- -0.053771283477544785
- 0.0
- -5.786525078543825e-11
- -4.296924361463228e-12
- 0.04988310486078262
- 0.2735360264778137
- 0.3780362904071808
- -0.3886977732181549
- 0.5943565964698792
- 0.0
- 0.0
- 0.0
- 0.2735360264778137
- -0.3780363202095032
- 0.38869768381118774
- 0.5943565964698792
- 0.0
- 0.0
- 0.0
- 0.021851519122719765
- 6.50993003235611e-19
- 0.0
- -0.0016183368861675262
- 0.03314746916294098
- 0.0
- 0.021851494908332825
- -6.50992279452575e-19
- 0.0
- -0.001618345850147307
- 0.033147480338811874
- 0.0
- -2.9577376676289644e-27
- -5.789850776845438e-26
- -0.017418665811419487
- 0.019857734441757202
- -1.1637140816865517e-18
- -1.015587747469384e-18
- -0.005069085396826267
- 0.0
- 0.0
- 0.0
- 0.019857637584209442
- 1.1637095321931826e-18
- 1.015587230481501e-18
- -0.0050690812058746815
- 0.0
- 0.0
- 0.0
motion_std:
- 0.3169145882129669
- 0.10599308460950851
- 0.10000000149011612
- 0.3133522868156433
- 0.23859412968158722
- 0.10000000149011612
- 0.3169146180152893
- 0.10599307715892792
- 0.10000000149011612
- 0.313352108001709
- 0.2385941445827484
- 0.10000000149011612
- 0.19965706765651703
- 0.10000000149011612
- 0.10000000149011612
- 0.22776634991168976
- 0.10000000149011612
- 0.21919523179531097
- 0.5675264000892639
- 0.10000000149011612
- 0.10000000149011612
- 0.10000000149011612
- 0.22776629030704498
- 0.10000000149011612
- 0.2191951721906662
- 0.5675263404846191
- 0.10000000149011612
- 0.10000000149011612
- 0.10000000149011612
- 2.0747177600860596
- 0.10000000149011612
- 0.10000000149011612
- 3.5380191802978516
- 2.4809296131134033
- 0.10000000149011612
- 2.0747175216674805
- 0.10000000149011612
- 0.10000000149011612
- 3.5380187034606934
- 2.4809298515319824
- 0.10000000149011612
- 0.10000000149011612
- 0.10000000149011612
- 0.41722986102104187
- 1.3870936632156372
- 0.10000000149011612
- 0.10000000149011612
- 1.4014573097229004
- 0.10000000149011612
- 0.10000000149011612
- 0.10000000149011612
- 1.3870937824249268
- 0.10000000149011612
- 0.10000000149011612
- 1.4014573097229004
- 0.10000000149011612
- 0.10000000149011612
- 0.10000000149011612
command_min:
- -0.23181389272212982
- -1.3701094388961792
- -4.481235980987549
command_max:
- 3.9783647060394287
- 1.3701094388961792
- 4.481235980987549
